apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-configmap
data:
  config-init.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "ecommerce"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = true
    "pid_file" = "/home/vault/.pid"

    "template" = {
      "destination" = "/vault/secrets/ecommerce"
      "contents" = <<EOT
      {{`{{- with secret "kv/data/ecommerce/postgres" -}}`}}
      export SPRING_DATASOURCE_USERNAME={{`{{ .Data.data.username }}`}}
      export SPRING_DATASOURCE_PASSWORD={{`{{ .Data.data.password }}`}}
      {{`{{- end }}`}}
      EOT
    }
  