name: Build and Push Image
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: cant-code/github-workflows/.github/workflows/java-spring-workflow.yml@main
    name: Build and verify
    with:
      SONAR_PROJECT_KEY: cant-code_parking-app-backend
      ARTIFACT_NAME: ecommerce
      ARTIFACT_PATH: target/ecommerce*.jar
    secrets: inherit

  create-image:
    name: Build Image and Push
    needs: build
    uses: cant-code/github-workflows/.github/workflows/docker-push.yml@main
    with:
      DOCKER_TAG: damnationcantcode/parking-space-backend
      ARTIFACT_NAME: ecommerce
      ARTIFACT_PATH: target
    secrets: inherit